// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9FP5k4cg82cNgPC7_moUhq3kdHlLIRi0',
    appId: '1:672454533907:web:5952ff60e6dabf41c3b0e6',
    messagingSenderId: '672454533907',
    projectId: 'project-kisan-32118',
    authDomain: 'project-kisan-32118.firebaseapp.com',
    storageBucket: 'project-kisan-32118.firebasestorage.app',
    measurementId: 'G-SSZD4XBTZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA121T3d7z-pk4vq1-ZAY98d_RuQ4toO2k',
    appId: '1:672454533907:android:3a45adc855e71ab3c3b0e6',
    messagingSenderId: '672454533907',
    projectId: 'project-kisan-32118',
    storageBucket: 'project-kisan-32118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzLas7Aw-rQbMrz81TQnoD8A0Is7SBIJU',
    appId: '1:672454533907:ios:d13f8a862b827186c3b0e6',
    messagingSenderId: '672454533907',
    projectId: 'project-kisan-32118',
    storageBucket: 'project-kisan-32118.firebasestorage.app',
    iosBundleId: 'com.example.projectKisan',
  );

}